"""initial agents schema

Revision ID: 5cfa842bbc44
Revises: 
Create Date: 2026-05-05 18:02:37.680213
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5cfa842bbc44'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('agent_id'),
    sa.UniqueConstraint('subject')
    )
    op.create_table('agent_endpoints',
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('endpoint_id', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('path_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('query_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('body_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('idempotent', sa.Boolean(), nullable=False),
    sa.CheckConstraint("mode IN ('block', 'stream')", name='ck_mode'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'endpoint_id')
    )
    op.create_table('agent_instances',
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('instance_id', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'instance_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_instances')
    op.drop_table('agent_endpoints')
    op.drop_table('agents')
    # ### end Alembic commands ###
