"""add audit_events table

Revision ID: 89fd1a83e294
Revises: 5cfa842bbc44
Create Date: 2026-05-05 18:22:20.353746
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '89fd1a83e294'
down_revision: Union[str, None] = '5cfa842bbc44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('request_id', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_subject', sa.String(length=255), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=True),
    sa.Column('endpoint_id', sa.String(length=255), nullable=True),
    sa.Column('instance_id', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('request_headers_digest', sa.Text(), nullable=True),
    sa.Column('response_headers_digest', sa.Text(), nullable=True),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_events')
    # ### end Alembic commands ###
