"""add routing_rules table

Revision ID: 98c78a39358b
Revises: 89fd1a83e294
Create Date: 2026-05-05 18:28:18.803736
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '98c78a39358b'
down_revision: Union[str, None] = '89fd1a83e294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routing_rules',
    sa.Column('rule_id', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('when_clause', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_agent_id', sa.String(length=255), nullable=False),
    sa.Column('target_instance_id', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('rule_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routing_rules')
    # ### end Alembic commands ###
